[project]
name = "opensearch-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.115.12",
    "greenlet>=3.1.1",
    "sqlalchemy>=2.0.39",
    "uvicorn>=0.34.0",
]
